"""add-log-entity

Revision ID: 747c4cee7ecb
Revises: ffc544c2bbe6
Create Date: 2019-11-08 09:51:31.400560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747c4cee7ecb'
down_revision = 'ffc544c2bbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('calendar_id', sa.Text(), nullable=False),
    sa.Column('subscriber_name', sa.Text(), nullable=False),
    sa.Column('subscription_method', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
