"""alter bouquets table

Revision ID: 8efbde3ecaeb
Revises: 747c4cee7ecb
Create Date: 2019-11-22 15:46:17.048484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efbde3ecaeb'
down_revision = '747c4cee7ecb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bouquets') as batch_op:
        batch_op.alter_column('auth_credentials', new_column_name='auth_uri')
        batch_op.alter_column('api_key1', new_column_name='token_uri')
        batch_op.alter_column('api_key2', new_column_name='client_id')

    with op.batch_alter_table('bouquets') as batch_op:
        batch_op.add_column(sa.Column('client_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('redirect_uris', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(), nullable=True))

    with op.batch_alter_table('bouquets') as batch_op:
        batch_op.alter_column('redirect_uris', nullable=False)
        batch_op.alter_column('client_secret', nullable=False)
        batch_op.alter_column('refresh_token', nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bouquets') as batch_op:
        batch_op.alter_column('auth_uri', new_column_name='auth_credentials')
        batch_op.alter_column('token_uri', new_column_name='api_key1')
        batch_op.alter_column('client_id', new_column_name='api_key2')

    with op.batch_alter_table('bouquets') as batch_op:
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('redirect_uris')
        batch_op.drop_column('client_secret')
    # ### end Alembic commands ###
