"""allow null values on channels table

Revision ID: 9f4ff449f825
Revises: ffc544c2bbe6
Create Date: 2019-09-11 14:19:44.002569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4ff449f825'
down_revision = 'ffc544c2bbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channels") as batch:
        batch.alter_column('channel_id',
                           existing_type=sa.VARCHAR(),
                           nullable=True)
        batch.alter_column('extra_atrributes',
                           existing_type=sa.VARCHAR(),
                           nullable=True)
        batch.alter_column('resource_id',
                           existing_type=sa.VARCHAR(),
                           nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channels") as batch:
        batch.alter_column('resource_id',
                           existing_type=sa.VARCHAR(),
                           nullable=False)
        batch.alter_column('extra_atrributes',
                           existing_type=sa.VARCHAR(),
                           nullable=False)
        batch.alter_column('channel_id',
                           existing_type=sa.VARCHAR(),
                           nullable=False)
    # ### end Alembic commands ###
