"""add bouquets table

Revision ID: ffc544c2bbe6
Revises: c5d7efe7e52c
Create Date: 2019-09-05 20:10:43.932347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc544c2bbe6'
down_revision = 'c5d7efe7e52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bouquets',
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bouquet_name', sa.String(), nullable=True),
    sa.Column('refresh_url', sa.String(), nullable=False),
    sa.Column('should_refresh', sa.Boolean(), nullable=True),
    sa.Column('api_key1', sa.String(), nullable=False),
    sa.Column('api_key2', sa.String(), nullable=False),
    sa.Column('auth_credentials', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bouquets')
    # ### end Alembic commands ###
